# Generated by Django 5.0.3 on 2024-03-27 10:08

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20)])),
                ('model', models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40)])),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50)])),
                ('summary', models.CharField(max_length=500, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('content', models.TextField()),
                ('max_speed', models.CharField(default='900', max_length=5)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_on'],
            },
        ),
    ]
