# Generated by Django 5.0.3 on 2024-03-27 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myexperience',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'My Experiences'},
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='brand',
            field=models.CharField(max_length=20, validators=[django.core.validators.MaxLengthValidator(20), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='model',
            field=models.CharField(max_length=40, validators=[django.core.validators.MaxLengthValidator(40), django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='myexperience',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(5)]),
        ),
    ]
