# Generated by Django 5.0.3 on 2024-03-27 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_myexperience_options_alter_myexperience_brand_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyExperience',
            new_name='Experience',
        ),
    ]
