# Generated by Django 5.0.3 on 2024-04-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_rename_myexperience_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
