# Generated by Django 5.0.3 on 2024-04-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_alter_experience_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Experiences'},
        ),
    ]
