# Generated by Django 5.0.3 on 2024-03-15 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=35)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=35)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Models',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='likes',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='likes',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_like', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
