# Generated by Django 5.0.3 on 2024-03-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehiclebrand_vehiclemodel_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemodel',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vehicle.vehiclebrand'),
            preserve_default=False,
        ),
    ]
