# Generated by Django 5.0.3 on 2024-03-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_vehiclemodel_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='cabin_type',
        ),
    ]
