# Generated by Django 5.0.3 on 2024-03-15 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_remove_vehicle_cabin_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='likes',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='vehicle_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
