# Generated by Django 5.0.3 on 2024-03-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_comment_vehicle_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='cc',
            field=models.CharField(default='10', max_length=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='hp',
            field=models.CharField(default='10', max_length=5),
        ),
    ]
