# Generated by Django 5.0.3 on 2024-03-23 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_alter_vehicle_cc_alter_vehicle_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_comments', to='vehicle.vehicle'),
        ),
    ]
