# Generated by Django 5.0.3 on 2024-03-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_comment_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='asd@asd.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='demo', max_length=100),
        ),
    ]
