# Generated by Django 5.0.3 on 2024-03-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_alter_comment_email_alter_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='acceleration',
            field=models.CharField(default='2.8', max_length=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_speed',
            field=models.CharField(default='900', max_length=5),
        ),
    ]
